"""nullable_phone_number

Revision ID: 110aa8f943a8
Revises: c8391dcd030c
Create Date: 2022-09-18 18:14:12.641208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110aa8f943a8'
down_revision = 'c8391dcd030c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###
