"""nullable_fields_on_user_data

Revision ID: c8391dcd030c
Revises: 8ccbf561a71d
Create Date: 2022-09-18 18:13:37.863594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8391dcd030c'
down_revision = '8ccbf561a71d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
